<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<PreserveCompilationContext>true</PreserveCompilationContext>  
	  
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Infrastructure\Email\Templates\JobApplicationNotification.cshtml" />
    <Content Remove="Infrastructure\Email\Templates\OtpVerification.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.NET-Next" Version="4.1.0" />
    <PackageReference Include="EPPlus" Version="8.5.4" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.25" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\JobPortal.Application\JobPortal.Application.csproj" />
    <ProjectReference Include="..\..\JobPortal.Infrastructure\JobPortal.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\resumes\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Infrastructure\Email\Templates\JobApplicationNotification.cshtml" />
    <None Include="Infrastructure\Email\Templates\OtpVerification.cshtml" />
  </ItemGroup>

</Project>
